sudo: required
language: generic

services:
  - docker

before_install:
  - sudo docker build -t mario010203/docker-react -f Dockerfile.dev .

script:
  - sudo docker run -e CI=true mario010203/docker-react npm run test